### ISSUE TITLE
64bit SendMessageW TNppDockingForm.RegisterDockingForm

### ISSUE THREAD

**Issue by ip74** [vladk1973/npp.connections#6]
In NppDockingForms.pas TNppDockingForm.RegisterDockingForm:

SendMessageW(self.Npp.NppData.NppHandle, NPPM_DMMREGASDCKDLG, 0, integer(@self.ToolbarData));

Should be:
SendMessageW(self.Npp.NppData.NppHandle, NPPM_DMMREGASDCKDLG, 0, lParam(@self.ToolbarData));

**Comment by AndyTheFactory** [comment]
Thanks for the tip! saved me a lot of headache!

**Comment by vladk1973** [comment]
Thanks!
Fixed
